name: FastAPI Backend CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Linting Check
        run: |
          flake8  # Adjust to your preferred linting tool

      - name: Static Type Checking
        run: |
          mypy your_project  # Adjust to your project structure

      - name: Test with Coverage
        run: |
          pytest --cov=workflowdemo tests/  # Adjust your test folder

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Post-Test Actions
        run: |
          # Add any additional post-test actions here
